POST http://localhost:5286/breakfasts
Content-Type: application/json

{
    "name": "Vegan Sunshine 2001",
    "description": "Vegan everything! Join us for healty breakfast.",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET https://localhost:7094/Breakfasts/6455bfb8-a6c9-47e3-ba04-32698dcaf4c3

//5eac4411-df0d-4ad3-a299-ccdb0f677d32
//0f1f0c62-9889-4000-bb0d-e66236109b71