@id=6455bfb8-a6c9-47e3-ba04-32698dcaf4c3

PUT http://localhost:5286/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 4Ecem Çivici 2001",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET http://localhost:5286/breakfasts/{{id}}